### ISSUE TITLE
通过安装命令报错

### ISSUE THREAD

**Issue by eason-su** [Serverless-Devs/Serverless-Devs#11]
命令：npm install -g @serverless-devs/s

错误信息：
```
npm ERR! Linux 3.10.0-1127.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "@serverless-devs/s"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/lib/node_modules/npm/lib/install/deps.js:455:12)
npm ERR! typeerror     at /usr/lib/node_modules/npm/lib/install/deps.js:456:7
npm ERR! typeerror     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/lib/node_modules/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/eason/sh/log/npm-debug.log
```

**Comment by wss-git** [comment]
看起来像是node 版本太低了，升级到 node >= v10 试试呢

**Comment by anycodes** [comment]
楼上的小伙伴回答的是正确的，是node的版本比较低。
