### ISSUE TITLE
The command s can't work

### ISSUE THREAD

**Issue by jsonbruce** [Serverless-Devs/Serverless-Devs#12]
**Environment**

- `macOS 11.0.1`
- `node v15.2.0`, `npm 7.0.10`
- `@serverless-devs/s@1.0.4`

**Description**

Run `s search` got below error:

```
➜  s search python

Search failed: Search failed, error: Request failed with status code 503
/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:75
                _a = this.checkVersionResult, status = _a.status, statusText = _a.statusText, data = _a.data;
                                                          ^

TypeError: Cannot read property 'status' of undefined
    at CheckVersion.<anonymous> (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:75:59)
    at step (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:34:23)
    at Object.next (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:15:53)
    at /usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:5:12)
    at CheckVersion.showMessage (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:71:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/command.js:188:42)
    at step (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/command.js:34:23)
    at Object.next (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/command.js:15:53)
```

Run `s gui` got similar error:

```
➜  s gui

Error: Request failed with status code 400
/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:75
                _a = this.checkVersionResult, status = _a.status, statusText = _a.statusText, data = _a.data;
                                                          ^

TypeError: Cannot read property 'status' of undefined
    at CheckVersion.<anonymous> (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:75:59)
    at step (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:34:23)
    at Object.next (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:15:53)
    at /usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:9:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:5:12)
    at CheckVersion.showMessage (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/check-version.js:71:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/command.js:188:42)
    at step (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/command.js:34:23)
    at Object.next (/usr/local/lib/node_modules/@serverless-devs/s/lib/utils/command.js:15:53)
```

Run `s -v` returns nothing:

```
➜  s -v


```

It seems there are some bugs in the `lib/utils/check-version.js` file.

**Comment by anycodes** [comment]
It should be caused by network problems.

Could you successfully open this page: `https://tool.serverlessfans.com/version`？

**Comment by jsonbruce** [comment]
Yes, I can access this URL:

![image](https://user-images.githubusercontent.com/15963141/99236380-16260b80-2832-11eb-958e-410e4c0526d9.png)

**Comment by anycodes** [comment]
Is there any problem with `s -v` now
