### ISSUE TITLE
Windows系统下s init命令报错

### ISSUE THREAD

**Issue by raykie** [Serverless-Devs/Serverless-Devs#173]
**错误场景**
Windows 10系统下执行`s init`指令

**截图**
![image](https://user-images.githubusercontent.com/51851458/130056542-dc2797be-3a81-4945-9fbd-46c42e1162d6.png)

**错误信息**
(node:15160) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at CheckVersion.<anonymous> (C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\check-version.js:74:59)
    at step (C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\check-version.js:33:23)
    at Object.next (C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\check-version.js:14:53)
    at C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\check-version.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\check-version.js:4:12)
    at CheckVersion.showMessage (C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\check-version.js:70:16)
    at Object.<anonymous> (C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\command.js:185:42)
    at step (C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\command.js:33:23)
    at Object.next (C:\Users\44393\AppData\Roaming\npm\node_modules\@serverless-dev\s\lib\utils\command.js:14:53)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15160) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by heimanba** [comment]
麻烦更新下版本 npm i @Serverless-Devs/s -g ,新版本应该不会出现这个问题
