### ISSUE TITLE
客户在window 下面运行一段时间报错

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/Serverless-Devs#239]
具体代码出现在
```
function copyAgain(p: string) {
  const packagePath = path.join(corePath, 'package.json');
  const packageInfo = readJsonFile(packagePath);
  const componentPackagePath = path.join(p, 'package.json');
  const componentPackageInfo = readJsonFile(componentPackagePath);
  return (
    componentPackageInfo && packageInfo && componentPackageInfo.version !== packageInfo.version
  );
}
```

出错信息
```
Unexpected end of JSON input\n
at JSON.parse (<anonymous>)\n
at readJsonFile (C:\\Users\\shang\\.s\\cache\\core\\dist\\index.js:1:91092)\n
at copyAgain (C:\\Users\\shang\\.s\\cache\\core\\dist\\index.js:1:48264)\n
at lns (C:\\Users\\shang\\.s\\cache\\core\\dist\\index.js:1:47869)\n
at C:\\Users\\shang\\.s\\cache\\core\\dist\\index.js:1:47214\n
at step (C:\\Users\\shang\\.s\\cache\\core\\dist\\index.js:1:46304)\n
at Object.next (C:\\Users\\shang\\.s\\cache\\core\\dist\\index.js:1:45589)\n
at C:\\Users\\shang\\.s\\cache\\core\\dist\\index.js:1:45273\n
at new Promise (<anonymous>)\n
at n (C:\\Users\\shang\\.s\\cache\\core\\dist\\index.js:1:45020)
```

**Comment by heimanba** [comment]
export function readJsonFile(filePath: string) {
  if (fs.existsSync(filePath)) {
    const data = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(data); //  util里面try-catch
  } else {
    logger.debug(`readJsonFile: the file ${filePath} does not exist`);
return null;
  }


![image](https://user-images.githubusercontent.com/5129967/138050607-bbac4b80-284c-464b-aa11-1bbb5bdef915.png)

}
