### ISSUE TITLE
新建应用 提示 Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by zjxpcyc** [Serverless-Devs/Serverless-Devs#395]
**Describe the bug**
首先，我不确定这是个 bug 。但是我什么也没操作，直接新建应用就报这个错误了
1、打开 desktop
2、切换到工作空间，选择新建应用
3、选择目录，我选择的是 `E:\work\go-sms\deploy`
4、点击确定，然后报错

内容如下:
```
- start downloading: https://registry.devsapp.cn/simple/devsapp/start-application/zipball/0.1.1
√ file decompression completed
(node:30012) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'E:\work\go-sms\deploy\1641820692826\s.yml'
    at Object.openSync (fs.js:466:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
    at Object.readFileSync (fs.js:368:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8592)
    at InitManager.<anonymous> (D:\Applications\ServerlessDesktop\resources\app.asar\node_modules\@sdesktop\s\lib\init\init-manager.js:80:64)
    at step (D:\Applications\ServerlessDesktop\resources\app.asar\node_modules\@sdesktop\s\lib\init\init-manager.js:33:23)
    at Object.next (D:\Applications\ServerlessDesktop\resources\app.asar\node_modules\@sdesktop\s\lib\init\init-manager.js:14:53)
    at D:\Applications\ServerlessDesktop\resources\app.asar\node_modules\@sdesktop\s\lib\init\init-manager.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\Applications\ServerlessDesktop\resources\app.asar\node_modules\@sdesktop\s\lib\init\init-manager.js:4:12)
(node:30012) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:30012) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Screenshots**
no

**Desktop (please complete the following information):**
 - OS: windows
 - Version 10

**Additional context**

desktop 找不到在哪看版本

```
s -v
@serverless-devs/s: 2.0.92, @serverless-devs/core: 0.1.10, win32-x64, node-v14.17.1
```

我进入 `E:\work\go-sms\deploy` 发现里面有2个文件夹，
* 1641820692826
* 16418206928261641820693313  我感觉这个目录创建的不对，不知道是不是

报错的内容是 `E:\work\go-sms\deploy\1641820692826\s.yml` 文件不存在。我进入之后发现 `s.yml` 文件在  `src` 里面。所以正确的目录应该是  `E:\work\go-sms\deploy\1641820692826\src\s.yml`  不知道这个对你们是不是有帮助

**Comment by heimanba** [comment]
1. 可以先升级下 cli的版本 npm i @serverless-devs/s -g
2. desktop有点bug, 麻烦先 使用 s init  进行创建哈。
