### ISSUE TITLE
Nuxt-app nodejs runtime does not support websocket

### ISSUE THREAD

**Issue by zhuang42** [Serverless-Devs/Serverless-Devs#517]
**Describe the bug**

**No longer valid, please see the comments**

> 
> I am using [nuxt-app](https://gitee.com/devsapp/start-web-framework/tree/master/web-framework/nodejs/nodejs-runtime/nuxt#https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2Fserverless-devs%2Fserverless-devs%2Fissues) to deploy my nuxt project. Everything went great except my proxy endpoint still requests the FC endpoint. 
> 
> **Screenshots**
> <img width="352" alt="image" src="https://user-images.githubusercontent.com/17071872/170845713-7f538230-8f2b-4cd5-92a3-3bde27366984.png">
> 
> For example, if I have my proxy settings like this, I expect to have my Axios will call `/api` to my `apiUrl` instead of the FC function domain. 
> 
> I am using the default example of `app.js` and `index.js` from the  [nuxt-app](https://gitee.com/devsapp/start-web-framework/tree/master/web-framework/nodejs/nodejs-runtime/nuxt#https://gitee.com/link?target=https%3A%2F%2Fgithub.com%2Fserverless-devs%2Fserverless-devs%2Fissues). Am I missing something to make it work in the nodejs runtime?
> 
> By the way, the Axios proxy works in the custom runtime, I guess it is because I didn't use `http-fc`?
> 
>
> Thanks
> 
> 
> **Desktop (please complete the following information):**
>  - OS: FC nodejs
>  - Version 14
> 
> **Additional context**
> N/A

**Comment by zhuang42** [comment]
Never mind, I think I misunderstood how the proxy works here at the beginning.

Here comes another problem, I am unable to connect to the WebSocket with socket.io. The FC function always timeout showed in the log. Error trace attached

```
2022-05-29 00:19:42 9a4544c6-aea2-430c-9291-75d52eaeea26 [error] (node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at HttpProxyMiddleware.catchUpgradeRequest (/code/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:63:24)
    at (/code/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:58:22)
    at next (null:null:null)
    at (/code/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:8:71)
    at Promise (null:null:null)
    at __awaiter (/code/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:4:12)
    at HttpProxyMiddleware.middleware (/code/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:26:47)
    at call (/code/node_modules/connect/index.js:239:7)
    at next (/code/node_modules/connect/index.js:183:5)
    at (/code/node_modules/http-proxy-middleware/dist/http-proxy-middleware.js:38:17)
```

The WebSocket is working using the customer runtime, so I think it might be something related to the http-fc limitation?

**Comment by zhuang42** [comment]
@heimanba 我找到了这个[`doc`](https://help.aliyun.com/document_detail/191345.html)，其中提到了只有custom runtime 和 custom container 支持websocket。

看起来应该是nodejs rumtime的限制。

**Comment by heimanba** [comment]
是的，框架层面不会做任何限制哈
