### ISSUE TITLE
Unclear error message in `s deploy`

### ISSUE THREAD

**Issue by ztl8702** [Serverless-Devs/Serverless-Devs#695]
**Describe the bug**
```
$ s deploy
✖ Message:

ERROR:

AssertionError [ERR_ASSERTION]: rimraf: missing path
    at Function.J0e [as sync] (/home/node/.s/cache/core/dist/index.js:99:15918)
    at e.<anonymous> (/home/node/.s/cache/core/dist/index.js:354:5479)
    at l (/home/node/.s/cache/core/dist/index.js:354:3629)
    at Object.next (/home/node/.s/cache/core/dist/index.js:354:2933)
    at o (/home/node/.s/cache/core/dist/index.js:354:2491)
```

`rimraf: missing path` is not an actionable error message

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux
 - Version [e.g. 22] `@serverless-devs/s: 2.1.11, core: 0.1.59, s-home: /home/node/.s, linux-x64, node-v16.19.1`

**Additional context**

**Comment by ztl8702** [comment]
这个应该如何debug？

**Comment by ztl8702** [comment]
似乎这样OK：

```
$ s clean --all
$ s deploy
```

但是之后再运行 `s deploy` 又是同样错误。也就是说，每次`s clean --all`之后，只能运行一次 deploy

**Comment by heimanba** [comment]
麻烦升级下 最新版本 `npm i @serverless-devs/s`看下哈？
