### ISSUE TITLE
s2tos3 异常 Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by dafang** [Serverless-Devs/Serverless-Devs#708]
**Describe the bug**
运行 `s cli fc3 s2tos3` 命令，异常：Cannot read properties of undefined (reading 'length')

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

```
[
  {
    "message": "Cannot read properties of undefined (reading 'length')",
    "exitCode": 101
  }
]
```
f3 cil logs:
 
[31mError Message:[39m
[31mCannot read properties of undefined (reading 'length')[39m
[2023-11-28 11:30:50][DEBUG] TypeError: Cannot read properties of undefined (reading 'length')
    at SYaml2To3._handle_fc_service (/root/.s/components/devsapp.cn/v3/fc3/dist/index.js:379:96182)
    at SYaml2To3._handle_fc (/root/.s/components/devsapp.cn/v3/fc3/dist/index.js:379:97546)
    at SYaml2To3._transform (/root/.s/components/devsapp.cn/v3/fc3/dist/index.js:379:95887)
    at SYaml2To3.<anonymous> (/root/.s/components/devsapp.cn/v3/fc3/dist/index.js:379:95802)
    at Generator.next (<anonymous>)
    at /root/.s/components/devsapp.cn/v3/fc3/dist/index.js:379:93645
    at new Promise (<anonymous>)
    at M (/root/.s/components/devsapp.cn/v3/fc3/dist/index.js:379:93392)
    at SYaml2To3.run (/root/.s/components/devsapp.cn/v3/fc3/dist/index.js:379:95534)
    at Fc.<anonymous> (/root/.s/components/devsapp.cn/v3/fc3/dist/index.js:379:41869)
 
Env:       @serverless-devs/s3: 0.1.0, linux-x64 node-v20.10.0                                   
Logs:      [4m/root/.s/logs/1128113048[24m                                                              
Get Help:  DingTalk: 33947367                                                                    
Feedback:  [36m[4mhttps://github.com/Serverless-Devs/Serverless-Devs/issues[24m[39m                             

[2023-11-28 11:31:48][DEBUG] Run traceid: 1128113048

**Comment by lowkeyrd** [comment]
可以脱敏发下s.yaml么，我们复现下

**Comment by heimanba** [comment]
暂未复现，新版的工具已经解决此类问题
