### ISSUE TITLE
Cannot find module 'raw-body'

### ISSUE THREAD

**Issue by www-YM** [Serverless-Devs/Serverless-Devs#829]
**Describe the bug**

通过 s init 指令`Alibaba Cloud Serverless` > `Quick start [Deploy a Hello World function to FaaS]` > `[HTTP] Node.js`创建的 nodejs14 项目。

1. 我只在示例项目的 index.js中添加引入 raw-body 的代码 `const rawBody = require('raw-body')`，
2. 然后`s local start`启动项目
3. 触发函数，直接提示错误：
```
2024-06-11T09:42:16.425Z 1-kk69sghx-s1dpk03q1gbwt4fhf6rgygrx [error] {"errorMessage":"Cannot find module 'raw-body'\nRequire stack:\n- /code/index.js\n- /var/fc/runtime/nodejs14_alinode/prepare_code.js\n- /var/fc/runtime/nodejs14_alinode/invoke.js\n- /var/fc/runtime/nodejs14_alinode/bootstrap.js","errorType":"FunctionUnhandledError: ImportModuleError","stackTrace":["Error: Cannot find module 'raw-body'","Require stack:","- /code/index.js","- /var/fc/runtime/nodejs14_alinode/prepare_code.js","- /var/fc/runtime/nodejs14_alinode/invoke.js","- /var/fc/runtime/nodejs14_alinode/bootstrap.js","    at Module._resolveFilename (internal/modules/cjs/loader.js:903:15)","    at Module._load (internal/modules/cjs/loader.js:747:27)","    at Module.require (internal/modules/cjs/loader.js:975:19)","    at require (internal/modules/cjs/helpers.js:93:18)","    at (/code/index.js:2:17)","    at Module._compile (internal/modules/cjs/loader.js:1086:14)","    at Module._extensions..js (internal/modules/cjs/loader.js:1115:10)","    at Module.load (internal/modules/cjs/loader.js:951:32)","    at Module._load (internal/modules/cjs/loader.js:791:12)","    at Module.require (internal/modules/cjs/loader.js:975:19)"]}
FC Invoke End RequestId: 1-kk69sghx-s1dpk03q1gbwt4fhf6rgygrx, Error: Unhandled function error
```

**Screenshots**

![image](https://github.com/Serverless-Devs/Serverless-Devs/assets/19513266/5ce65b76-858e-456f-b17f-83a2e45d7731)

<img width="1214" alt="image" src="https://github.com/Serverless-Devs/Serverless-Devs/assets/19513266/f58647bb-d305-4769-905a-ba1943522c7a">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS

**Additional context**
s --version: @serverless-devs/s: 3.0.9, s-home: /home/yiming/.s, linux-x64, node-v18.13.0

**Comment by zxypro1** [comment]
函数内使用新的库是需要加依赖的。可以在本地创建一个包含raw-body的层上传到FC，然后在s.yaml里加上这个层。可参考https://manual.serverless-devs.com/user-guide/aliyun/fc3/layer/

**Comment by www-YM** [comment]
> 函数内使用新的库是需要加依赖的。可以在本地创建一个包含raw-body的层上传到FC，然后在s.yaml里加上这个层。可参考https://manual.serverless-devs.com/user-guide/aliyun/fc3/layer/

我看到在官方文档里已经写明内置模块里包含了 raw-body。
https://help.aliyun.com/zh/functioncompute/user-guide/runtime-overview-1

<img width="1149" alt="image" src="https://github.com/Serverless-Devs/Serverless-Devs/assets/19513266/9351d268-6251-4dd8-a755-29bc2f418a8e">

----------

后面我在 s.yaml 上声明了环境变量就可以使用内置的模块了。这个是本来就应该在运行环境里面默认声明，漏掉了吗？

<img width="557" alt="image" src="https://github.com/Serverless-Devs/Serverless-Devs/assets/19513266/a6cd55e9-d0e4-40ed-89ac-58dd79446be4">

**Comment by anycodes** [comment]
@zxypro1 烦请多关注一下github issue，另外如果已经确定完成的issue，烦请及时close

**Comment by zxypro1** [comment]
> > 函数内使用新的库是需要加依赖的。可以在本地创建一个包含raw-body的层上传到FC，然后在s.yaml里加上这个层。可参考https://manual.serverless-devs.com/user-guide/aliyun/fc3/layer/
> 
> 我看到在官方文档里已经写明内置模块里包含了 raw-body。 https://help.aliyun.com/zh/functioncompute/user-guide/runtime-overview-1
> 
> <img alt="image" width="1149" src="https://private-user-images.githubusercontent.com/19513266/339721780-9351d268-6251-4dd8-a755-29bc2f418a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDk5OTMsIm5iZiI6MTcyMDE0OTY5MywicGF0aCI6Ii8xOTUxMzI2Ni8zMzk3MjE3ODAtOTM1MWQyNjgtNjI1MS00ZGQ4LWE3NTUtMjliYzJmNDE4YThlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAzMjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0OTExNTRhNDFjYjRkN2Q3ZWI4YmJhMWJiMTIyMDY2M2Q2NWJiMjczY2Y1MWQxYTg1ZGQzNjFlZWIzNmQyNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lTKgrfNTjGvnfp9lFxqKHB4oKUS0qHKk3LlEwPVTkfE">
> 后面我在 s.yaml 上声明了环境变量就可以使用内置的模块了。这个是本来就应该在运行环境里面默认声明，漏掉了吗？
> 
> <img alt="image" width="557" src="https://private-user-images.githubusercontent.com/19513266/339724451-a6cd55e9-d0e4-40ed-89ac-58dd79446be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDk5OTMsIm5iZiI6MTcyMDE0OTY5MywicGF0aCI6Ii8xOTUxMzI2Ni8zMzk3MjQ0NTEtYTZjZDU1ZTktZDBlNC00MGVkLTg5YWMtNThkZDc5NDQ2YmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAzMjEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMmZjMTUzNmY4MWVmYjM0ZTUzZTk2MTViYzNhMTM3MDRkYTk1ZWExMTM5OGIyYjAxZTkxYTc4MWUyYzI0NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6W4CcXEGKIx8_6Nyb4Nso23hYQcHrtYwgg5m9xk3t44">

目前这个quick start模版是不支持node18和20的，是你自己修改了runtime吗？
