### ISSUE TITLE
s local invoke Unexpected token '??='

### ISSUE THREAD

**Issue by badboy-tian** [Serverless-Devs/Serverless-Devs#870]
```
╰─➤  s local invoke {\"packId\":\"c4zXKmrVAWIUeT5e5fSQ6M5q\"}
[2024-09-12 22:30:39] [INFO] [FC-CORE] - Skip pulling image registry.cn-shanghai.aliyuncs.com/xxxxx/xxxxx...
[object Object]
[2024-09-12 22:30:39] [INFO] [FC-LOCAL-INVOKE] - Exiting Container...
/usr/src/node_modules/undici/lib/core/util.js:623
  const listeners = (obj[kListeners] ??= [])
                                     ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/src/node_modules/undici/lib/dispatcher/client.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[2024-09-12 22:30:40] [INFO] [FC-LOCAL-INVOKE] - Container exited!

Tips for next step
======================
* Deploy Resources: s deploy
helloworld: 
  status: succeed

```

版本
```
Macos 13.6.9 (22G830)
Node: v21.5.0
s: @serverless-devs/s: 2.2.1, core: 0.1.62, s-home: /Users/tian/.s, darwin-x64, node-v21.5.0
```

**Comment by badboy-tian** [comment]
如果安装3.0的话 运行的时候直接卡死 s depoly 控制台无法用 ctrl+c 退出
<img width="232" alt="image" src="https://github.com/user-attachments/assets/64909111-168c-4c9f-b0f7-7b66f695c3aa">

**Comment by zxypro1** [comment]
可以删除一下~/.s，再用3.0试一下

**Comment by zxypro1** [comment]
config信息需要重新配一下

**Comment by badboy-tian** [comment]
删除~/.s, 解决
