### ISSUE TITLE
阿里云FC应用模板部署video-flow应用失败，返回403错误 "the caller is not authorized to perform fnf:DescribeFlow"

### ISSUE THREAD

**Issue by shuyu108** [Serverless-Devs/Serverless-Devs#877]
**Describe the bug**
阿里云FC应用模板部署 [video-flow](https://github.com/devsapp/start-ffmpeg/tree/V3/video-flow) 应用失败。
报错信息
```
✔ [oss-trigger-workflow] completed (1.65s)
✖ [multimedia-process-v3-workflow] failed to [deploy] (0.97s)
 
✖ [multimedia-process-v3-workflow] failed to [deploy]:
====================
Error Message:
Error: AccessDenied: code: 403, the caller is not authorized to perform 'fnf:DescribeFlow' on resource 'acs:fnf:cn-hangzhou:${token-account-uid}:flow/multimedia-process-flow-7ped' request id: bfdf4c19-5020-aac8-d4a0-63d2ee68da4c
 
A complete log of this run can be found in: /root/.s/logs/1009191334
 
Env:       @serverless-devs/s3: 3.1.1, linux-x64 node-v16.16.0                
Logs:      /root/.s/logs/1009191334                                           
Feedback:  https://github.com/Serverless-Devs/Serverless-Devs/issues          

Error
    at Deploy.<anonymous> (/tmp/cache/plugins/@serverless-cd/s-deploy/node_modules/@serverless-cd/s-deploy/lib/deploy.js:41:23)
    at Generator.throw (<anonymous>)
    at rejected (/tmp/cache/plugins/@serverless-cd/s-deploy/node_modules/@serverless-cd/s-deploy/lib/deploy.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Cleaning up task
```

**Screenshots**
<img width="714" alt="截屏2024-10-09 19 15 16" src="https://github.com/user-attachments/assets/72858141-7d98-41ab-96ad-3b3c84de379b">

**Desktop (please complete the following information):**
使用阿里云函数计算FC 3.0控制台的应用模板: https://fcnext.console.aliyun.com/applications/create?template=multimedia-process-flow-v3

**Additional context**

**Comment by zxypro1** [comment]
应该是账号没有开通FNF的权限，可以开通一下

**Comment by shuyu108** [comment]
谢谢回复，后来可以了。应用模板的角色固定为 `AliyunFCServerlessDevsRole `。把FNF的权限策略加到这个角色之后可以部署了。
