### ISSUE TITLE
Failed when build FC3.0 in macos

### ISSUE THREAD

**Issue by izhangzhihao** [Serverless-Devs/Serverless-Devs#882]
s build --use-docker -t s.staging.yaml

it works well when build FC2.0

```
[2024-10-25 18:25:12][INFO][test-staging-oss-sample-function] runCommand ===>  
docker pull registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.10:build-3.1.0 
e761c5128332: Already exists
fa488706ea13: Already exists
fae29f309a72: Already exists
09c3d7cc89f6: Already exists
8f3ff589edc2: Already exists
620af4e91dbf: Already exists
66f6c9eea021: Already exists
0b5db87f5b42: Already exists
172d5a7e6834: Already exists
234a814752a2: Already exists
f632004fb5d4: Already exists
fdab5c5d31a7: Already exists
3294b084210e: Already exists
fcdc0f5f890f: Already exists
4b9856a7d515: Already exists
889cdb86a8a7: Already exists
4f4fb700ef54: Already exists
eecfcfc8dfad: Already exists
9c64494fc14b: Already exists
4f4fb700ef54: Already exists
23f7f640f2c6: Already exists
785b28b468aa: Already exists
4f4fb700ef54: Already exists
28fca74d99b6: Already exists
719bfd446b41: Pulling fs layer
719bfd446b41: Download complete
719bfd446b41: Download complete
registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.10:build-3.1.0
[2024-10-25 18:25:13][INFO][test-staging-oss-sample-function] runCommand ===>  
docker run --platform linux/amd64 --rm  -v /Users/izhangzhihao/builds/uCrYxJwvv/0/shareservice/share-service-report/function-compute-3/test-oss-sample-function/code:/code registry.cn-beijing.aliyuncs.com/aliyunfc/runtime-python3.10:build-3.1.0 bash -c "pip install -t python -r requirements.txt --upgrade "
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting pandas
  Downloading https://mirrors.aliyun.com/pypi/packages/44/50/7db2cd5e6373ae796f0ddad3675268c8d59fb6076e66f0c339d61cea886b/pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 18.0 MB/s eta 0:00:00
Collecting tzdata>=2022.7
  Downloading https://mirrors.aliyun.com/pypi/packages/a6/ab/7e5f53c3b9d14972843a647d8d7a853969a58aecc7559cb3267302c94774/tzdata-2024.2-py2.py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 15.6 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.2
  Downloading https://mirrors.aliyun.com/pypi/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 24.3 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading https://mirrors.aliyun.com/pypi/packages/11/c3/005fcca25ce078d2cc29fd559379817424e94885510568bc1bc53d7d5846/pytz-2024.2-py2.py3-none-any.whl (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.0/508.0 kB 52.9 MB/s eta 0:00:00
Collecting numpy>=1.22.4
  Downloading https://mirrors.aliyun.com/pypi/packages/fb/25/ba023652a39a2c127200e85aed975fc6119b421e2c348e5d0171e2046edb/numpy-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.3/16.3 MB 16.9 MB/s eta 0:00:00
Collecting six>=1.5
  Downloading https://mirrors.aliyun.com/pypi/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
Successfully installed numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 six-1.16.0 tzdata-2024.2
ERROR: Exception:
Traceback (most recent call last):
  File "/var/fc/lang/python3.10/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/tmp/pip-target-1du604zn/lib/python/pytz' -> '/code/python/pytz'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/var/fc/lang/python3.10/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/var/fc/lang/python3.10/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/var/fc/lang/python3.10/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 553, in run
    self._handle_target_dir(
  File "/var/fc/lang/python3.10/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 612, in _handle_target_dir
    shutil.move(os.path.join(lib_dir, item), target_item_dir)
  File "/var/fc/lang/python3.10/lib/python3.10/shutil.py", line 832, in move
    copytree(src, real_dst, copy_function=copy_function,
  File "/var/fc/lang/python3.10/lib/python3.10/shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/var/fc/lang/python3.10/lib/python3.10/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/tmp/pip-target-1du604zn/lib/python/pytz/__init__.py', '/code/python/pytz/__init__.py', "[Errno 13] Permission denied: '/code/python/pytz/__init__.py'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/exceptions.py', '/code/python/pytz/exceptions.py', "[Errno 13] Permission denied: '/code/python/pytz/exceptions.py'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/lazy.py', '/code/python/pytz/lazy.py', "[Errno 13] Permission denied: '/code/python/pytz/lazy.py'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/reference.py', '/code/python/pytz/reference.py', "[Errno 13] Permission denied: '/code/python/pytz/reference.py'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/tzfile.py', '/code/python/pytz/tzfile.py', "[Errno 13] Permission denied: '/code/python/pytz/tzfile.py'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/tzinfo.py', '/code/python/pytz/tzinfo.py', "[Errno 13] Permission denied: '/code/python/pytz/tzinfo.py'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/CET', '/code/python/pytz/zoneinfo/CET', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/CET'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/CST6CDT', '/code/python/pytz/zoneinfo/CST6CDT', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/CST6CDT'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Cuba', '/code/python/pytz/zoneinfo/Cuba', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Cuba'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/EET', '/code/python/pytz/zoneinfo/EET', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/EET'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/EST', '/code/python/pytz/zoneinfo/EST', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/EST'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/EST5EDT', '/code/python/pytz/zoneinfo/EST5EDT', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/EST5EDT'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Egypt', '/code/python/pytz/zoneinfo/Egypt', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Egypt'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Eire', '/code/python/pytz/zoneinfo/Eire', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Eire'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Factory', '/code/python/pytz/zoneinfo/Factory', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Factory'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/GB', '/code/python/pytz/zoneinfo/GB', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/GB'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/GB-Eire', '/code/python/pytz/zoneinfo/GB-Eire', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/GB-Eire'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/GMT', '/code/python/pytz/zoneinfo/GMT', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/GMT'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/GMT+0', '/code/python/pytz/zoneinfo/GMT+0', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/GMT+0'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/GMT-0', '/code/python/pytz/zoneinfo/GMT-0', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/GMT-0'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/GMT0', '/code/python/pytz/zoneinfo/GMT0', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/GMT0'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Greenwich', '/code/python/pytz/zoneinfo/Greenwich', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Greenwich'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/HST', '/code/python/pytz/zoneinfo/HST', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/HST'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Hongkong', '/code/python/pytz/zoneinfo/Hongkong', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Hongkong'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Iceland', '/code/python/pytz/zoneinfo/Iceland', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Iceland'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Iran', '/code/python/pytz/zoneinfo/Iran', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Iran'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Israel', '/code/python/pytz/zoneinfo/Israel', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Israel'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Jamaica', '/code/python/pytz/zoneinfo/Jamaica', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Jamaica'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Japan', '/code/python/pytz/zoneinfo/Japan', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Japan'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Kwajalein', '/code/python/pytz/zoneinfo/Kwajalein', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Kwajalein'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Libya', '/code/python/pytz/zoneinfo/Libya', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Libya'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/MET', '/code/python/pytz/zoneinfo/MET', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/MET'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/MST', '/code/python/pytz/zoneinfo/MST', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/MST'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/MST7MDT', '/code/python/pytz/zoneinfo/MST7MDT', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/MST7MDT'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/NZ', '/code/python/pytz/zoneinfo/NZ', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/NZ'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/NZ-CHAT', '/code/python/pytz/zoneinfo/NZ-CHAT', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/NZ-CHAT'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Navajo', '/code/python/pytz/zoneinfo/Navajo', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Navajo'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/PRC', '/code/python/pytz/zoneinfo/PRC', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/PRC'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/PST8PDT', '/code/python/pytz/zoneinfo/PST8PDT', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/PST8PDT'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Poland', '/code/python/pytz/zoneinfo/Poland', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Poland'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Portugal', '/code/python/pytz/zoneinfo/Portugal', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Portugal'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/ROC', '/code/python/pytz/zoneinfo/ROC', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/ROC'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/ROK', '/code/python/pytz/zoneinfo/ROK', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/ROK'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Singapore', '/code/python/pytz/zoneinfo/Singapore', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Singapore'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Turkey', '/code/python/pytz/zoneinfo/Turkey', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Turkey'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/UCT', '/code/python/pytz/zoneinfo/UCT', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/UCT'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/UTC', '/code/python/pytz/zoneinfo/UTC', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/UTC'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Universal', '/code/python/pytz/zoneinfo/Universal', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Universal'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/W-SU', '/code/python/pytz/zoneinfo/W-SU', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/W-SU'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/WET', '/code/python/pytz/zoneinfo/WET', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/WET'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Zulu', '/code/python/pytz/zoneinfo/Zulu', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Zulu'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/iso3166.tab', '/code/python/pytz/zoneinfo/iso3166.tab', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/iso3166.tab'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/leapseconds', '/code/python/pytz/zoneinfo/leapseconds', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/leapseconds'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/tzdata.zi', '/code/python/pytz/zoneinfo/tzdata.zi', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/tzdata.zi'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/zone.tab', '/code/python/pytz/zoneinfo/zone.tab', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/zone.tab'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/zone1970.tab', '/code/python/pytz/zoneinfo/zone1970.tab', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/zone1970.tab'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/zonenow.tab', '/code/python/pytz/zoneinfo/zonenow.tab', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/zonenow.tab'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Africa/Abidjan', '/code/python/pytz/zoneinfo/Africa/Abidjan', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Africa/Abidjan'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Africa/Accra', '/code/python/pytz/zoneinfo/Africa/Accra', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Africa/Accra'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Africa/Addis_Ababa', '/code/python/pytz/zoneinfo/Africa/Addis_Ababa', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Africa/Addis_Ababa'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Africa/Algiers', '/code/python/pytz/zoneinfo/Africa/Algiers', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Africa/Algiers'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Africa/Asmara', '/code/python/pytz/zoneinfo/Africa/Asmara', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Africa/Asmara'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/zoneinfo/Africa/Asmera', '/code/python/pytz/zoneinfo/Africa/Asmera', "[Errno 13] Permission denied: '/code/python/pytz/zoneinfo/Africa/Asmera'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/__pycache__/tzfile.cpython-310.pyc', '/code/python/pytz/__pycache__/tzfile.cpython-310.pyc', "[Errno 13] Permission denied: '/code/python/pytz/__pycache__/tzfile.cpython-310.pyc'"), ('/tmp/pip-target-1du604zn/lib/python/pytz/__pycache__/tzinfo.cpython-310.pyc', '/code/python/pytz/__pycache__/tzinfo.cpython-310.pyc', "[Errno 13] Permission denied: '/code/python/pytz/__pycache__/tzinfo.cpython-310.pyc'"), (<DirEntry '__pycache__'>, '/code/python/pytz/__pycache__', "[Errno 13] Permission denied: '/code/python/pytz/__pycache__'"), ('/tmp/pip-target-1du604zn/lib/python/pytz', '/code/python/pytz', "[Errno 13] Permission denied: '/code/python/pytz'")]
[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
✖ [test-staging-oss-sample-function] failed to [build] (16s)
 
✖ [test-staging-oss-sample-function] failed to [build]:
====================
Error Message:
command failed with code 2
 
A complete log of this run can be found in: /Users/izhangzhihao/.s/logs/1025182511
 
Env:       @serverless-devs/s: 3.1.1, darwin-x64 node-v20.5.0                 
Logs:      /Users/izhangzhihao/.s/logs/1025182511                             
Feedback:  https://github.com/Serverless-Devs/Serverless-Devs/issues   
```

**Comment by izhangzhihao** [comment]
podman -v
podman version 5.2.5

**Comment by rsonghuster** [comment]
能贴下您这边可以复现问题的 requirements.txt 吗

**Comment by izhangzhihao** [comment]
```
-i https://mirrors.aliyun.com/pypi/simple/
pandas
```
